import { config, fields, collection, singleton } from '@keystatic/core';

const githubRepo = (process.env.KEYSTATIC_GITHUB_REPO ?? 'KCB-Labs/labs.kcb.ma') as `${string}/${string}`;

export default config({
  storage: {
    kind: 'github',
    repo: githubRepo,
  },
  collections: {
    labs: collection({
      label: 'Labs',
      slugField: 'title',
      path: 'src/content/labs/*',
      format: { contentField: 'content' },
      schema: {
        title: fields.slug({ name: { label: 'Title', validation: { isRequired: true } } }),
        description: fields.text({ label: 'Short Description', validation: { isRequired: true } }),
        status: fields.select({
          label: 'Status',
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Exploring', value: 'exploring' },
            { label: 'Paused', value: 'paused' },
            { label: 'Archived', value: 'archived' },
          ],
          defaultValue: 'active',
        }),
        published: fields.checkbox({ label: 'Published', defaultValue: false }),
        publishedAt: fields.datetime({ label: 'Published At' }),
        updatedAt: fields.datetime({ label: 'Updated At' }),
        content: fields.markdoc({ label: 'Content' }),
        research: fields.array(fields.relationship({ label: 'Research', collection: 'research' }), {
          label: 'Research',
          itemLabel: (props) => props.value ?? 'Research',
        }),
        experiments: fields.array(fields.relationship({ label: 'Experiments', collection: 'experiments' }), {
          label: 'Experiments',
          itemLabel: (props) => props.value ?? 'Experiment',
        }),
        projects: fields.array(fields.relationship({ label: 'Projects', collection: 'projects' }), {
          label: 'Projects',
          itemLabel: (props) => props.value ?? 'Project',
        }),
        technologies: fields.array(fields.text({ label: 'Technology' }), {
          label: 'Technologies',
          itemLabel: (props) => props.value,
        }),
        featured: fields.checkbox({ label: 'Featured', defaultValue: false }),
        priority: fields.integer({ label: 'Priority' }),
        ratingKnowledge: fields.integer({ label: 'Knowledge Rating', validation: { isRequired: true } }),
        ratingCreativity: fields.integer({ label: 'Creativity Rating', validation: { isRequired: true } }),
        ratingBusiness: fields.integer({ label: 'Business Rating', validation: { isRequired: true } }),
        tags: fields.array(fields.text({ label: 'Tag' }), {
          label: 'Tags',
          itemLabel: (props) => props.value,
        }),
        seoTitle: fields.text({ label: 'SEO Title' }),
        seoDescription: fields.text({ label: 'SEO Description', multiline: true }),
        socialImage: fields.image({ label: 'Social Image', directory: 'src/assets/labs', publicPath: '../../assets/labs/' }),
        socialImageAlt: fields.text({ label: 'Social Image Alt' }),
      },
    }),
    research: collection({
      label: 'Research',
      slugField: 'title',
      path: 'src/content/research/*',
      format: { contentField: 'content' },
      schema: {
        title: fields.slug({ name: { label: 'Title', validation: { isRequired: true } } }),
        description: fields.text({ label: 'Short Description', validation: { isRequired: true } }),
        status: fields.select({
          label: 'Status',
          options: [
            { label: 'Draft', value: 'draft' },
            { label: 'Active', value: 'active' },
            { label: 'Published', value: 'published' },
            { label: 'Archived', value: 'archived' },
          ],
          defaultValue: 'active',
        }),
        published: fields.checkbox({ label: 'Published', defaultValue: false }),
        publishedAt: fields.datetime({ label: 'Published At' }),
        updatedAt: fields.datetime({ label: 'Updated At' }),
        content: fields.markdoc({ label: 'Content' }),
        lab: fields.relationship({ label: 'Lab', collection: 'labs' }),
        experiments: fields.array(fields.relationship({ label: 'Experiments', collection: 'experiments' }), {
          label: 'Experiments',
          itemLabel: (props) => props.value ?? 'Experiment',
        }),
        projects: fields.array(fields.relationship({ label: 'Projects', collection: 'projects' }), {
          label: 'Projects',
          itemLabel: (props) => props.value ?? 'Project',
        }),
        question: fields.text({ label: 'Research Question', multiline: true }),
        hypothesis: fields.text({ label: 'Hypothesis', multiline: true }),
        featured: fields.checkbox({ label: 'Featured', defaultValue: false }),
        priority: fields.integer({ label: 'Priority' }),
        ratingKnowledge: fields.integer({ label: 'Knowledge Rating', validation: { isRequired: true } }),
        ratingCreativity: fields.integer({ label: 'Creativity Rating', validation: { isRequired: true } }),
        ratingBusiness: fields.integer({ label: 'Business Rating', validation: { isRequired: true } }),
        tags: fields.array(fields.text({ label: 'Tag' }), {
          label: 'Tags',
          itemLabel: (props) => props.value,
        }),
        seoTitle: fields.text({ label: 'SEO Title' }),
        seoDescription: fields.text({ label: 'SEO Description', multiline: true }),
        socialImage: fields.image({ label: 'Social Image', directory: 'src/assets/research', publicPath: '../../assets/research/' }),
        socialImageAlt: fields.text({ label: 'Social Image Alt' }),
      },
    }),
    experiments: collection({
      label: 'Experiments',
      slugField: 'title',
      path: 'src/content/experiments/*',
      format: { contentField: 'content' },
      schema: {
        title: fields.slug({ name: { label: 'Title', validation: { isRequired: true } } }),
        description: fields.text({ label: 'Short Description', validation: { isRequired: true } }),
        status: fields.select({
          label: 'Status',
          options: [
            { label: 'Draft', value: 'draft' },
            { label: 'Active', value: 'active' },
            { label: 'Published', value: 'published' },
            { label: 'Archived', value: 'archived' },
          ],
          defaultValue: 'active',
        }),
        outcome: fields.select({
          label: 'Outcome',
          options: [
            { label: 'Validated', value: 'VALIDATED' },
            { label: 'Inconclusive', value: 'INCONCLUSIVE' },
            { label: 'Failed', value: 'FAILED' },
            { label: 'Partial', value: 'PARTIAL' },
          ],
          defaultValue: 'INCONCLUSIVE',
        }),
        published: fields.checkbox({ label: 'Published', defaultValue: false }),
        publishedAt: fields.datetime({ label: 'Published At' }),
        updatedAt: fields.datetime({ label: 'Updated At' }),
        content: fields.markdoc({ label: 'Content' }),
        lab: fields.relationship({ label: 'Lab', collection: 'labs' }),
        research: fields.array(fields.relationship({ label: 'Research', collection: 'research' }), {
          label: 'Research',
          itemLabel: (props) => props.value ?? 'Research',
        }),
        project: fields.relationship({ label: 'Project', collection: 'projects' }),
        objective: fields.text({ label: 'Objective', multiline: true }),
        featured: fields.checkbox({ label: 'Featured', defaultValue: false }),
        priority: fields.integer({ label: 'Priority' }),
        ratingKnowledge: fields.integer({ label: 'Knowledge Rating', validation: { isRequired: true } }),
        ratingCreativity: fields.integer({ label: 'Creativity Rating', validation: { isRequired: true } }),
        ratingBusiness: fields.integer({ label: 'Business Rating', validation: { isRequired: true } }),
        tags: fields.array(fields.text({ label: 'Tag' }), {
          label: 'Tags',
          itemLabel: (props) => props.value,
        }),
        seoTitle: fields.text({ label: 'SEO Title' }),
        seoDescription: fields.text({ label: 'SEO Description', multiline: true }),
        socialImage: fields.image({ label: 'Social Image', directory: 'src/assets/experiments', publicPath: '../../assets/experiments/' }),
        socialImageAlt: fields.text({ label: 'Social Image Alt' }),
      },
    }),
    projects: collection({
      label: 'Projects',
      slugField: 'title',
      path: 'src/content/projects/*',
      format: { contentField: 'content' },
      schema: {
        title: fields.slug({ name: { label: 'Title', validation: { isRequired: true } } }),
        description: fields.text({ label: 'Short Description', validation: { isRequired: true } }),
        type: fields.select({
          label: 'Type',
          options: [
            { label: 'Internal', value: 'Internal' },
            { label: 'Client', value: 'Client' },
            { label: 'Startup', value: 'Startup' },
            { label: 'Collaboration', value: 'Collaboration' },
            { label: 'Open Source', value: 'Open Source' },
            { label: 'Research', value: 'Research' },
          ],
          defaultValue: 'Internal',
        }),
        stage: fields.select({
          label: 'Stage',
          options: [
            { label: 'Idea', value: 'Idea' },
            { label: 'Validating', value: 'Validating' },
            { label: 'Validated', value: 'Validated' },
            { label: 'Implementation', value: 'Implementation' },
            { label: 'Live', value: 'Live' },
            { label: 'Completed', value: 'Completed' },
            { label: 'Spun Out', value: 'Spun Out' },
            { label: 'Archived', value: 'Archived' },
          ],
          defaultValue: 'Idea',
        }),
        status: fields.select({
          label: 'Status',
          options: [
            { label: 'Draft', value: 'draft' },
            { label: 'Active', value: 'active' },
            { label: 'Published', value: 'published' },
            { label: 'Archived', value: 'archived' },
          ],
          defaultValue: 'active',
        }),
        published: fields.checkbox({ label: 'Published', defaultValue: false }),
        publishedAt: fields.datetime({ label: 'Published At' }),
        updatedAt: fields.datetime({ label: 'Updated At' }),
        content: fields.markdoc({ label: 'Content' }),
        originLab: fields.relationship({ label: 'Origin Lab', collection: 'labs' }),
        research: fields.array(fields.relationship({ label: 'Research', collection: 'research' }), {
          label: 'Research',
          itemLabel: (props) => props.value ?? 'Research',
        }),
        experiments: fields.array(fields.relationship({ label: 'Experiments', collection: 'experiments' }), {
          label: 'Experiments',
          itemLabel: (props) => props.value ?? 'Experiment',
        }),
        featured: fields.checkbox({ label: 'Featured', defaultValue: false }),
        priority: fields.integer({ label: 'Priority' }),
        ratingKnowledge: fields.integer({ label: 'Knowledge Rating', validation: { isRequired: true } }),
        ratingCreativity: fields.integer({ label: 'Creativity Rating', validation: { isRequired: true } }),
        ratingBusiness: fields.integer({ label: 'Business Rating', validation: { isRequired: true } }),
        tags: fields.array(fields.text({ label: 'Tag' }), {
          label: 'Tags',
          itemLabel: (props) => props.value,
        }),
        seoTitle: fields.text({ label: 'SEO Title' }),
        seoDescription: fields.text({ label: 'SEO Description', multiline: true }),
        socialImage: fields.image({ label: 'Social Image', directory: 'src/assets/projects', publicPath: '../../assets/projects/' }),
        socialImageAlt: fields.text({ label: 'Social Image Alt' }),
      },
    }),
    articles: collection({
      label: 'Articles',
      slugField: 'title',
      path: 'src/content/articles/*',
      format: { contentField: 'content' },
      schema: {
        title: fields.slug({ name: { label: 'Title', validation: { isRequired: true } } }),
        description: fields.text({ label: 'Short Description', validation: { isRequired: true } }),
        category: fields.select({
          label: 'Category',
          options: [
            { label: 'Article', value: 'Article' },
            { label: 'Lab Note', value: 'Lab Note' },
            { label: 'Field Note', value: 'Field Note' },
            { label: 'Perspective', value: 'Perspective' },
            { label: 'Announcement', value: 'Announcement' },
          ],
          defaultValue: 'Article',
        }),
        status: fields.select({
          label: 'Status',
          options: [
            { label: 'Draft', value: 'draft' },
            { label: 'Active', value: 'active' },
            { label: 'Published', value: 'published' },
            { label: 'Archived', value: 'archived' },
          ],
          defaultValue: 'draft',
        }),
        published: fields.checkbox({ label: 'Published', defaultValue: false }),
        publishedAt: fields.datetime({ label: 'Published At' }),
        updatedAt: fields.datetime({ label: 'Updated At' }),
        content: fields.markdoc({ label: 'Content' }),
        author: fields.relationship({ label: 'Author', collection: 'people' }),
        labs: fields.array(fields.relationship({ label: 'Labs', collection: 'labs' }), {
          label: 'Labs',
          itemLabel: (props) => props.value ?? 'Lab',
        }),
        research: fields.array(fields.relationship({ label: 'Research', collection: 'research' }), {
          label: 'Research',
          itemLabel: (props) => props.value ?? 'Research',
        }),
        experiments: fields.array(fields.relationship({ label: 'Experiments', collection: 'experiments' }), {
          label: 'Experiments',
          itemLabel: (props) => props.value ?? 'Experiment',
        }),
        projects: fields.array(fields.relationship({ label: 'Projects', collection: 'projects' }), {
          label: 'Projects',
          itemLabel: (props) => props.value ?? 'Project',
        }),
        people: fields.array(fields.relationship({ label: 'People', collection: 'people' }), {
          label: 'People',
          itemLabel: (props) => props.value ?? 'Person',
        }),
        organizations: fields.array(fields.relationship({ label: 'Organizations', collection: 'organizations' }), {
          label: 'Organizations',
          itemLabel: (props) => props.value ?? 'Organization',
        }),
        featured: fields.checkbox({ label: 'Featured', defaultValue: false }),
        priority: fields.integer({ label: 'Priority' }),
        tags: fields.array(fields.text({ label: 'Tag' }), {
          label: 'Tags',
          itemLabel: (props) => props.value,
        }),
        seoTitle: fields.text({ label: 'SEO Title' }),
        seoDescription: fields.text({ label: 'SEO Description', multiline: true }),
        socialImage: fields.image({ label: 'Social Image', directory: 'src/assets/articles', publicPath: '../../assets/articles/' }),
        socialImageAlt: fields.text({ label: 'Social Image Alt' }),
      },
    }),
    people: collection({
      label: 'People',
      slugField: 'title',
      path: 'src/content/people/*',
      format: { contentField: 'content' },
      schema: {
        title: fields.slug({ name: { label: 'Name', validation: { isRequired: true } } }),
        description: fields.text({ label: 'Short Bio', validation: { isRequired: true } }),
        role: fields.text({ label: 'Role' }),
        status: fields.select({
          label: 'Status',
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Inactive', value: 'inactive' },
          ],
          defaultValue: 'active',
        }),
        published: fields.checkbox({ label: 'Published', defaultValue: false }),
        publishedAt: fields.datetime({ label: 'Published At' }),
        updatedAt: fields.datetime({ label: 'Updated At' }),
        content: fields.markdoc({ label: 'Bio' }),
        avatar: fields.image({ label: 'Avatar', directory: 'src/assets/people', publicPath: '../../assets/people/' }),
        avatarAlt: fields.text({ label: 'Avatar Alt' }),
        website: fields.url({ label: 'Website' }),
        linkedin: fields.url({ label: 'LinkedIn' }),
        github: fields.url({ label: 'GitHub' }),
        x: fields.url({ label: 'X (Twitter)' }),
        featured: fields.checkbox({ label: 'Featured', defaultValue: false }),
        order: fields.integer({ label: 'Order' }),
        relatedLabs: fields.array(fields.relationship({ label: 'Labs', collection: 'labs' }), {
          label: 'Related Labs',
          itemLabel: (props) => props.value ?? 'Lab',
        }),
        relatedProjects: fields.array(fields.relationship({ label: 'Projects', collection: 'projects' }), {
          label: 'Related Projects',
          itemLabel: (props) => props.value ?? 'Project',
        }),
        priority: fields.integer({ label: 'Priority' }),
        tags: fields.array(fields.text({ label: 'Tag' }), {
          label: 'Tags',
          itemLabel: (props) => props.value,
        }),
        seoTitle: fields.text({ label: 'SEO Title' }),
        seoDescription: fields.text({ label: 'SEO Description', multiline: true }),
        socialImage: fields.image({ label: 'Social Image', directory: 'src/assets/people', publicPath: '../../assets/people/' }),
        socialImageAlt: fields.text({ label: 'Social Image Alt' }),
      },
    }),
    organizations: collection({
      label: 'Organizations',
      slugField: 'title',
      path: 'src/content/organizations/*',
      format: { contentField: 'content' },
      schema: {
        title: fields.slug({ name: { label: 'Name', validation: { isRequired: true } } }),
        description: fields.text({ label: 'Description', validation: { isRequired: true } }),
        type: fields.select({
          label: 'Type',
          options: [
            { label: 'Partner', value: 'Partner' },
            { label: 'Client', value: 'Client' },
            { label: 'Sponsor', value: 'Sponsor' },
            { label: 'Startup', value: 'Startup' },
            { label: 'University', value: 'University' },
            { label: 'Research Organization', value: 'Research Organization' },
            { label: 'Technology Partner', value: 'Technology Partner' },
            { label: 'Community', value: 'Community' },
            { label: 'Open Source Community', value: 'Open Source Community' },
          ],
          defaultValue: 'Partner',
        }),
        status: fields.select({
          label: 'Status',
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Inactive', value: 'inactive' },
          ],
          defaultValue: 'active',
        }),
        published: fields.checkbox({ label: 'Published', defaultValue: false }),
        publishedAt: fields.datetime({ label: 'Published At' }),
        updatedAt: fields.datetime({ label: 'Updated At' }),
        content: fields.markdoc({ label: 'Content' }),
        logo: fields.image({ label: 'Logo', directory: 'src/assets/organizations', publicPath: '../../assets/organizations/' }),
        logoAlt: fields.text({ label: 'Logo Alt' }),
        website: fields.url({ label: 'Website' }),
        relationship: fields.text({ label: 'Relationship', multiline: true }),
        relatedLabs: fields.array(fields.relationship({ label: 'Labs', collection: 'labs' }), {
          label: 'Related Labs',
          itemLabel: (props) => props.value ?? 'Lab',
        }),
        relatedProjects: fields.array(fields.relationship({ label: 'Projects', collection: 'projects' }), {
          label: 'Related Projects',
          itemLabel: (props) => props.value ?? 'Project',
        }),
        featured: fields.checkbox({ label: 'Featured', defaultValue: false }),
        priority: fields.integer({ label: 'Priority' }),
        tags: fields.array(fields.text({ label: 'Tag' }), {
          label: 'Tags',
          itemLabel: (props) => props.value,
        }),
        seoTitle: fields.text({ label: 'SEO Title' }),
        seoDescription: fields.text({ label: 'SEO Description', multiline: true }),
        socialImage: fields.image({ label: 'Social Image', directory: 'src/assets/organizations', publicPath: '../../assets/organizations/' }),
        socialImageAlt: fields.text({ label: 'Social Image Alt' }),
      },
    }),
    opensource: collection({
      label: 'Open Source',
      slugField: 'title',
      path: 'src/content/opensource/*',
      format: { contentField: 'content' },
      schema: {
        title: fields.slug({ name: { label: 'Name', validation: { isRequired: true } } }),
        description: fields.text({ label: 'Description', validation: { isRequired: true } }),
        status: fields.select({
          label: 'Status',
          options: [
            { label: 'Active', value: 'active' },
            { label: 'Maintained', value: 'maintained' },
            { label: 'Archived', value: 'archived' },
          ],
          defaultValue: 'active',
        }),
        published: fields.checkbox({ label: 'Published', defaultValue: false }),
        publishedAt: fields.datetime({ label: 'Published At' }),
        updatedAt: fields.datetime({ label: 'Updated At' }),
        content: fields.markdoc({ label: 'Documentation' }),
        repository: fields.url({ label: 'Repository' }),
        license: fields.text({ label: 'License' }),
        originLab: fields.relationship({ label: 'Origin Lab', collection: 'labs' }),
        relatedProject: fields.relationship({ label: 'Related Project', collection: 'projects' }),
        technologies: fields.array(fields.text({ label: 'Technology' }), {
          label: 'Technologies',
          itemLabel: (props) => props.value,
        }),
        featured: fields.checkbox({ label: 'Featured', defaultValue: false }),
        priority: fields.integer({ label: 'Priority' }),
        ratingKnowledge: fields.integer({ label: 'Knowledge Rating', validation: { isRequired: true } }),
        ratingCreativity: fields.integer({ label: 'Creativity Rating', validation: { isRequired: true } }),
        ratingBusiness: fields.integer({ label: 'Business Rating', validation: { isRequired: true } }),
        tags: fields.array(fields.text({ label: 'Tag' }), {
          label: 'Tags',
          itemLabel: (props) => props.value,
        }),
        seoTitle: fields.text({ label: 'SEO Title' }),
        seoDescription: fields.text({ label: 'SEO Description', multiline: true }),
        socialImage: fields.image({ label: 'Social Image', directory: 'src/assets/opensource', publicPath: '../../assets/opensource/' }),
        socialImageAlt: fields.text({ label: 'Social Image Alt' }),
      },
    }),
    roadmap: collection({
      label: 'Roadmap',
      slugField: 'title',
      path: 'src/content/roadmap/*',
      format: { contentField: 'content' },
      schema: {
        title: fields.slug({ name: { label: 'Period', validation: { isRequired: true } } }),
        description: fields.text({ label: 'Theme', validation: { isRequired: true } }),
        status: fields.select({
          label: 'Status',
          options: [
            { label: 'Planned', value: 'planned' },
            { label: 'Active', value: 'active' },
            { label: 'Completed', value: 'completed' },
          ],
          defaultValue: 'planned',
        }),
        published: fields.checkbox({ label: 'Published', defaultValue: false }),
        publishedAt: fields.datetime({ label: 'Published At' }),
        updatedAt: fields.datetime({ label: 'Updated At' }),
        content: fields.markdoc({ label: 'Content' }),
        period: fields.text({ label: 'Period' }),
        theme: fields.text({ label: 'Theme' }),
        objective: fields.text({ label: 'Objective', multiline: true }),
        areas: fields.array(fields.text({ label: 'Area' }), {
          label: 'Areas of Exploration',
          itemLabel: (props) => props.value,
        }),
        featured: fields.checkbox({ label: 'Featured', defaultValue: false }),
        priority: fields.integer({ label: 'Priority' }),
        tags: fields.array(fields.text({ label: 'Tag' }), {
          label: 'Tags',
          itemLabel: (props) => props.value,
        }),
        seoTitle: fields.text({ label: 'SEO Title' }),
        seoDescription: fields.text({ label: 'SEO Description', multiline: true }),
        socialImage: fields.image({ label: 'Social Image', directory: 'src/assets/roadmap', publicPath: '../../assets/roadmap/' }),
        socialImageAlt: fields.text({ label: 'Social Image Alt' }),
      },
    }),
  },
  singletons: {
    site: singleton({
      label: 'Site',
      path: 'src/content/site',
      format: { data: 'yaml' },
      schema: {
        title: fields.text({ label: 'Site Title' }),
        description: fields.text({ label: 'Site Description', multiline: true }),
        seoTitle: fields.text({ label: 'SEO Title' }),
        seoDescription: fields.text({ label: 'SEO Description', multiline: true }),
      },
    }),
    about: singleton({
      label: 'About',
      path: 'src/content/pages/about',
      format: { data: 'yaml' },
      schema: {
        title: fields.text({ label: 'Title' }),
        description: fields.text({ label: 'Description', multiline: true }),
        content: fields.markdoc({ label: 'Content' }),
      },
    }),
    vision: singleton({
      label: 'Vision',
      path: 'src/content/pages/vision',
      format: { data: 'yaml' },
      schema: {
        title: fields.text({ label: 'Title' }),
        description: fields.text({ label: 'Description', multiline: true }),
        content: fields.markdoc({ label: 'Content' }),
      },
    }),
    sponsorship: singleton({
      label: 'Sponsorship',
      path: 'src/content/pages/sponsorship',
      format: { data: 'yaml' },
      schema: {
        title: fields.text({ label: 'Title' }),
        description: fields.text({ label: 'Description', multiline: true }),
        content: fields.markdoc({ label: 'Content' }),
      },
    }),
    settings: singleton({
      label: 'Settings',
      path: 'src/content/settings',
      format: { data: 'yaml' },
      schema: {
        siteUrl: fields.url({ label: 'Site URL' }),
        analyticsProvider: fields.select({
          label: 'Analytics Provider',
          options: [
            { label: 'Plausible', value: 'plausible' },
            { label: 'Umami', value: 'umami' },
            { label: 'None', value: 'none' },
          ],
          defaultValue: 'none',
        }),
      },
    }),
  },
});
